[package]
name = "exchange_rate_path"
version = "0.1.0"
authors = ["Lachezar Lechev <elpiel93@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"

[dependencies.petgraph]
version = "0.4.13"
features = ["graphmap"]